/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/g1d3LxTwdjM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"

export function GenerateImageForm() {
  return (
    <div className="max-w-4xl mx-auto p-8 sm:p-12 lg:p-16">
      <h1 className="text-3xl font-bold mb-8">Faceswap Generator</h1>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div>
          <h2 className="text-xl font-bold mb-4">Upload Your Photo</h2>
          <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-6 flex flex-col items-center justify-center">
            <img
              alt="Uploaded Image"
              className="rounded-lg"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/300",
                objectFit: "cover",
              }}
              width={300}
            />
          </div>
        </div>
        <div>
          <h2 className="text-xl font-bold mb-4">Select Your Gender</h2>
          <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-6 flex flex-col items-center justify-center">
            <div className="flex items-center gap-4">
              <Label className="flex items-center gap-2 font-normal">Male</Label>
              <Label className="flex items-center gap-2 font-normal">Female</Label>
            </div>
          </div>
        </div>
      </div>
      <div className="mt-8">
        <h2 className="text-xl font-bold mb-4">Select a Style</h2>
        <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-6 grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4" />
      </div>
      <div className="mt-8">
        <h2 className="text-xl font-bold mb-4">Your Faceswap</h2>
        <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-6 flex items-center justify-center">
          <img
            alt="Faceswap Image"
            className="rounded-lg"
            height={500}
            src="/placeholder.svg"
            style={{
              aspectRatio: "500/500",
              objectFit: "cover",
            }}
            width={500}
          />
        </div>
      </div>
    </div>
  )
}
