/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/GlEZ9zfxbpm
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Textarea } from "@/components/ui/textarea"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Slider } from "@/components/ui/slider"
import { Button } from "@/components/ui/button"

export function ImageGenerator() {
  return (
    <div className="grid grid-cols-1 md:grid-cols-[300px_1fr] gap-8 p-8 w-full max-w-6xl mx-auto">
      <div className="bg-white dark:bg-gray-950 rounded-lg shadow-lg p-6 space-y-6">
        <div>
          <h2 className="text-2xl font-bold">Generate Image</h2>
          <p className="text-gray-500 dark:text-gray-400">Enter a prompt and select a style to generate an image.</p>
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300" htmlFor="prompt">
            Prompt
          </label>
          <Textarea
            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-gray-500 focus:ring-gray-500 dark:bg-gray-800 dark:border-gray-700 dark:focus:border-gray-600 dark:focus:ring-gray-600"
            id="prompt"
            name="prompt"
            placeholder="Describe the image you want to generate..."
            rows={3}
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300" htmlFor="style">
            Style
          </label>
          <Select
            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-gray-500 focus:ring-gray-500 dark:bg-gray-800 dark:border-gray-700 dark:focus:border-gray-600 dark:focus:ring-gray-600"
            id="style"
            name="style"
          >
            <SelectTrigger>
              <SelectValue placeholder="Select a style" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="impressionist">Impressionist</SelectItem>
              <SelectItem value="surrealist">Surrealist</SelectItem>
              <SelectItem value="abstract">Abstract</SelectItem>
              <SelectItem value="photorealistic">Photorealistic</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300" htmlFor="size">
            Image Size
          </label>
          <Select
            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-gray-500 focus:ring-gray-500 dark:bg-gray-800 dark:border-gray-700 dark:focus:border-gray-600 dark:focus:ring-gray-600"
            id="size"
            name="size"
          >
            <SelectTrigger>
              <SelectValue placeholder="Select a size" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="small">Small (512x512)</SelectItem>
              <SelectItem value="medium">Medium (768x768)</SelectItem>
              <SelectItem value="large">Large (1024x1024)</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300" htmlFor="resolution">
            Resolution
          </label>
          <Slider className="mt-1" defaultValue={[50]} id="resolution" max={100} min={0} name="resolution" step={10} />
        </div>
        <Button
          className="w-full bg-gray-900 text-white hover:bg-gray-800 focus:ring-gray-500 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-200 dark:focus:ring-gray-600"
          type="submit"
        >
          Generate Image
        </Button>
      </div>
      <div className="bg-white dark:bg-gray-950 rounded-lg shadow-lg p-6 space-y-6">
        <div>
          <h2 className="text-2xl font-bold">Generated Image</h2>
          <p className="text-gray-500 dark:text-gray-400">Your generated image will be displayed here.</p>
        </div>
        <div className="aspect-square bg-gray-100 dark:bg-gray-800 rounded-lg overflow-hidden flex items-center justify-center">
          <img
            alt="Generated Image"
            className="w-full h-full object-contain"
            height={512}
            src="/placeholder.svg"
            style={{
              aspectRatio: "512/512",
              objectFit: "cover",
            }}
            width={512}
          />
        </div>
      </div>
      <div className="bg-white dark:bg-gray-950 rounded-lg shadow-lg p-6 space-y-6 col-span-1 md:col-span-2">
        <div>
          <h2 className="text-2xl font-bold">Gallery</h2>
          <p className="text-gray-500 dark:text-gray-400">View your previously generated images.</p>
        </div>
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
          <div className="aspect-square bg-gray-100 dark:bg-gray-800 rounded-lg overflow-hidden flex items-center justify-center">
            <img
              alt="Generated Image"
              className="w-full h-full object-contain"
              height={256}
              src="/placeholder.svg"
              style={{
                aspectRatio: "256/256",
                objectFit: "cover",
              }}
              width={256}
            />
          </div>
          <div className="aspect-square bg-gray-100 dark:bg-gray-800 rounded-lg overflow-hidden flex items-center justify-center">
            <img
              alt="Generated Image"
              className="w-full h-full object-contain"
              height={256}
              src="/placeholder.svg"
              style={{
                aspectRatio: "256/256",
                objectFit: "cover",
              }}
              width={256}
            />
          </div>
          <div className="aspect-square bg-gray-100 dark:bg-gray-800 rounded-lg overflow-hidden flex items-center justify-center">
            <img
              alt="Generated Image"
              className="w-full h-full object-contain"
              height={256}
              src="/placeholder.svg"
              style={{
                aspectRatio: "256/256",
                objectFit: "cover",
              }}
              width={256}
            />
          </div>
          <div className="aspect-square bg-gray-100 dark:bg-gray-800 rounded-lg overflow-hidden flex items-center justify-center">
            <img
              alt="Generated Image"
              className="w-full h-full object-contain"
              height={256}
              src="/placeholder.svg"
              style={{
                aspectRatio: "256/256",
                objectFit: "cover",
              }}
              width={256}
            />
          </div>
        </div>
      </div>
    </div>
  )
}
